# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_scale_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectScaleWindow(object):
    def setupUi(self, SelectScaleWindow):
        SelectScaleWindow.setObjectName("SelectScaleWindow")
        SelectScaleWindow.resize(1024, 1024)
        self.image = QtWidgets.QGraphicsView(SelectScaleWindow)
        self.image.setGeometry(QtCore.QRect(0, 0, 1024, 1024))
        self.image.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.image.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.image.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.image.setInteractive(True)
        self.image.setObjectName("image")
        self.label = QtWidgets.QLabel(SelectScaleWindow)
        self.label.setGeometry(QtCore.QRect(330, 430, 411, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")

        self.retranslateUi(SelectScaleWindow)
        QtCore.QMetaObject.connectSlotsByName(SelectScaleWindow)

    def retranslateUi(self, SelectScaleWindow):
        _translate = QtCore.QCoreApplication.translate
        SelectScaleWindow.setWindowTitle(_translate("SelectScaleWindow", "Form"))
        self.label.setText(_translate("SelectScaleWindow", "Click the two endpoints of the scale bar"))
