# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_designs\select_scale_bar.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SelectScale(object):
    def setupUi(self, SelectScale):
        SelectScale.setObjectName("SelectScale")
        SelectScale.resize(1024, 1024)
        self.image = QtWidgets.QGraphicsView(SelectScale)
        self.image.setGeometry(QtCore.QRect(0, 0, 1024, 1024))
        self.image.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.image.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.image.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.image.setInteractive(True)
        self.image.setObjectName("image")
        self.label = QtWidgets.QLabel(SelectScale)
        self.label.setGeometry(QtCore.QRect(330, 430, 411, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")

        self.retranslateUi(SelectScale)
        QtCore.QMetaObject.connectSlotsByName(SelectScale)

    def retranslateUi(self, SelectScale):
        _translate = QtCore.QCoreApplication.translate
        SelectScale.setWindowTitle(_translate("SelectScale", "Form"))
        self.label.setText(_translate("SelectScale", "Click the two endpoints of the scale bar"))
