# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_scale_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_set_scale_window(object):
    def setupUi(self, set_scale_window):
        set_scale_window.setObjectName("set_scale_window")
        set_scale_window.resize(306, 327)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(set_scale_window.sizePolicy().hasHeightForWidth())
        set_scale_window.setSizePolicy(sizePolicy)
        set_scale_window.setToolTipDuration(-1)
        self.buttonBox = QtWidgets.QDialogButtonBox(set_scale_window)
        self.buttonBox.setGeometry(QtCore.QRect(0, 290, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.setScaleInputField_1 = QtWidgets.QLineEdit(set_scale_window)
        self.setScaleInputField_1.setGeometry(QtCore.QRect(160, 30, 121, 22))
        self.setScaleInputField_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.setScaleInputField_1.setText("")
        self.setScaleInputField_1.setObjectName("setScaleInputField_1")
        self.setScaleInputField_2 = QtWidgets.QLineEdit(set_scale_window)
        self.setScaleInputField_2.setGeometry(QtCore.QRect(160, 70, 121, 22))
        self.setScaleInputField_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.setScaleInputField_2.setText("")
        self.setScaleInputField_2.setObjectName("setScaleInputField_2")
        self.setScaleInputField_3 = QtWidgets.QLineEdit(set_scale_window)
        self.setScaleInputField_3.setGeometry(QtCore.QRect(160, 110, 121, 22))
        self.setScaleInputField_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.setScaleInputField_3.setText("")
        self.setScaleInputField_3.setObjectName("setScaleInputField_3")
        self.Label_1 = QtWidgets.QLabel(set_scale_window)
        self.Label_1.setGeometry(QtCore.QRect(30, 30, 151, 19))
        self.Label_1.setObjectName("Label_1")
        self.label_2 = QtWidgets.QLabel(set_scale_window)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 111, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(set_scale_window)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 121, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(set_scale_window)
        self.pushButton.setGeometry(QtCore.QRect(160, 150, 87, 27))
        self.pushButton.setObjectName("pushButton")
        self.label_scale_result = QtWidgets.QLabel(set_scale_window)
        self.label_scale_result.setGeometry(QtCore.QRect(70, 240, 171, 21))
        self.label_scale_result.setObjectName("label_scale_result")

        self.retranslateUi(set_scale_window)
        self.buttonBox.accepted.connect(set_scale_window.accept) # type: ignore
        self.buttonBox.rejected.connect(set_scale_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(set_scale_window)

    def retranslateUi(self, set_scale_window):
        _translate = QtCore.QCoreApplication.translate
        set_scale_window.setWindowTitle(_translate("set_scale_window", "Set Scale"))
        self.setScaleInputField_1.setPlaceholderText(_translate("set_scale_window", " Enter value"))
        self.setScaleInputField_2.setPlaceholderText(_translate("set_scale_window", " Enter value"))
        self.setScaleInputField_3.setPlaceholderText(_translate("set_scale_window", " Enter value"))
        self.Label_1.setText(_translate("set_scale_window", "Distance in pixels:"))
        self.label_2.setText(_translate("set_scale_window", "Known distance:"))
        self.label_3.setText(_translate("set_scale_window", "Pixel aspect rato:"))
        self.pushButton.setText(_translate("set_scale_window", "Clear"))
        self.label_scale_result.setText(_translate("set_scale_window", "Scale: 71.984 pixels/unit"))
