# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set_scale_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_set_scale_window(object):
    def setupUi(self, set_scale_window):
        set_scale_window.setObjectName("set_scale_window")
        set_scale_window.resize(306, 327)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(set_scale_window.sizePolicy().hasHeightForWidth())
        set_scale_window.setSizePolicy(sizePolicy)
        set_scale_window.setToolTipDuration(-1)
        self.buttonBox = QtWidgets.QDialogButtonBox(set_scale_window)
        self.buttonBox.setGeometry(QtCore.QRect(0, 290, 301, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.setScaleInputField_DistanceInPixels = QtWidgets.QLineEdit(set_scale_window)
        self.setScaleInputField_DistanceInPixels.setGeometry(QtCore.QRect(160, 30, 121, 22))
        self.setScaleInputField_DistanceInPixels.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.setScaleInputField_DistanceInPixels.setText("")
        self.setScaleInputField_DistanceInPixels.setObjectName("setScaleInputField_DistanceInPixels")
        self.setScaleInputField_KnownDistance = QtWidgets.QLineEdit(set_scale_window)
        self.setScaleInputField_KnownDistance.setGeometry(QtCore.QRect(160, 70, 121, 22))
        self.setScaleInputField_KnownDistance.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.setScaleInputField_KnownDistance.setText("")
        self.setScaleInputField_KnownDistance.setObjectName("setScaleInputField_KnownDistance")
        self.setScaleInputField_PixelRatio = QtWidgets.QLineEdit(set_scale_window)
        self.setScaleInputField_PixelRatio.setGeometry(QtCore.QRect(160, 110, 121, 22))
        self.setScaleInputField_PixelRatio.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.setScaleInputField_PixelRatio.setText("")
        self.setScaleInputField_PixelRatio.setObjectName("setScaleInputField_PixelRatio")
        self.Label_1 = QtWidgets.QLabel(set_scale_window)
        self.Label_1.setGeometry(QtCore.QRect(30, 30, 151, 19))
        self.Label_1.setObjectName("Label_1")
        self.label_2 = QtWidgets.QLabel(set_scale_window)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 111, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(set_scale_window)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 121, 19))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(set_scale_window)
        self.pushButton.setGeometry(QtCore.QRect(160, 180, 87, 27))
        self.pushButton.setObjectName("pushButton")
        self.label_scale = QtWidgets.QLabel(set_scale_window)
        self.label_scale.setGeometry(QtCore.QRect(80, 240, 51, 16))
        self.label_scale.setObjectName("label_scale")
        self.setScaleInputField_Unit = QtWidgets.QLineEdit(set_scale_window)
        self.setScaleInputField_Unit.setGeometry(QtCore.QRect(160, 150, 121, 22))
        self.setScaleInputField_Unit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.setScaleInputField_Unit.setText("")
        self.setScaleInputField_Unit.setObjectName("setScaleInputField_Unit")
        self.label_4 = QtWidgets.QLabel(set_scale_window)
        self.label_4.setGeometry(QtCore.QRect(60, 150, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.label_scale_result = QtWidgets.QLabel(set_scale_window)
        self.label_scale_result.setGeometry(QtCore.QRect(130, 240, 51, 16))
        self.label_scale_result.setObjectName("label_scale_result")
        self.label_scale_unit = QtWidgets.QLabel(set_scale_window)
        self.label_scale_unit.setGeometry(QtCore.QRect(180, 240, 81, 16))
        self.label_scale_unit.setObjectName("label_scale_unit")

        self.retranslateUi(set_scale_window)
        self.buttonBox.accepted.connect(set_scale_window.accept) # type: ignore
        self.buttonBox.rejected.connect(set_scale_window.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(set_scale_window)

    def retranslateUi(self, set_scale_window):
        _translate = QtCore.QCoreApplication.translate
        set_scale_window.setWindowTitle(_translate("set_scale_window", "Set Scale"))
        self.setScaleInputField_DistanceInPixels.setPlaceholderText(_translate("set_scale_window", " Enter value"))
        self.setScaleInputField_KnownDistance.setPlaceholderText(_translate("set_scale_window", " Enter value"))
        self.setScaleInputField_PixelRatio.setPlaceholderText(_translate("set_scale_window", " Enter value"))
        self.Label_1.setText(_translate("set_scale_window", "Distance in pixels:"))
        self.label_2.setText(_translate("set_scale_window", "Known distance:"))
        self.label_3.setText(_translate("set_scale_window", "Pixel aspect rato:"))
        self.pushButton.setText(_translate("set_scale_window", "Clear"))
        self.label_scale.setText(_translate("set_scale_window", "Scale:"))
        self.setScaleInputField_Unit.setPlaceholderText(_translate("set_scale_window", " Enter value"))
        self.label_4.setText(_translate("set_scale_window", "Unit of length:"))
        self.label_scale_result.setText(_translate("set_scale_window", "71.984"))
        self.label_scale_unit.setText(_translate("set_scale_window", "pixels/unit"))
